### ISSUE TITLE
Add optional request parameters for reviews, recommendations, characters, actors, etc.

### ISSUE THREAD

**Issue by seanblue** [croberts22/railgun#38]
Feel free to close this issue if you don't want to do this. I hope you'll make some new data like reviews, recommendations, characters, and actors optional and add request parameters for them. In my case, I don't need that data, so making them optional could reduce the response's payload by around 90%.

**Comment by croberts22** [comment]
Yeah, definitely an idea I want to mess with at some point. It's a bit similar to what I've detailed in #19. I'm juggling ideas between creating resource-specific endpoints (i.e. anime/<anime_id>/reviews) and returning a brief subset of data, with an href to fetch the the whole list a la HAL style.
